<a href="https://colab.research.google.com/github/wirtes/gittest/blob/main/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list = [3, 2, 5]
sorted(my_list)

[2, 3, 5]

# Some Markdown
## And a bit more
without stylte

In [1]:
>>> import tensorflow as tf
>>> x = tf.ones(shape=(2, 1))     

>>> print(x)
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
>>> x = tf.zeros(shape=(2, 1))    

>>> print(x)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


TypeError: ignored